encoding: utf-8
markdown: kramdown
pygments: true
permalink: none
baseurl: ""
exclude:
- .gitignore
- README.md
- run.sh


author: 4711

prose:
  rooturl: "_posts"
  metadata:
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: johndoe
      author: John Doe
      categories:
      - articles